# Generated by Django 4.1.10 on 2023-07-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_input', models.CharField(max_length=200)),
                ('tc_output', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('problem_name', models.CharField(max_length=200)),
                ('problem_description', models.TextField()),
                ('problem_attempted', models.BooleanField(default=False)),
                ('test_cases', models.ManyToManyField(to='question.test_case')),
            ],
        ),
    ]
