# Generated by Django 4.1.10 on 2023-07-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='problem_attempted',
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_memorylimit',
            field=models.IntegerField(default=8, help_text='in MB'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_timelimit',
            field=models.IntegerField(default=2, help_text='in seconds'),
        ),
    ]
