# Generated by Django 4.1.10 on 2023-07-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_remove_problem_problem_attempted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('user_name', models.CharField(max_length=50)),
                ('problem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('problem_name', models.CharField(max_length=200)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('language_used', models.CharField(max_length=10)),
                ('input_code', models.TextField()),
            ],
        ),
    ]
