# Generated by Django 4.1.10 on 2023-07-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
